# Generated by Django 6.0.4 on 2026-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cravely_app', '0003_recipe_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='', help_text='Seperate steps with |'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Summary of dish'),
        ),
    ]
