# Generated by Django 6.0.4 on 2026-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cravely_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_by', to='cravely_app.ingredient'),
        ),
    ]
